---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      conda_env_name: ansible-conda-env-test
      conda_env_environment: ansible-conda-env-test-environment.yml
      conda_env_cleanup: true
      conda_env_activate_for_login_shell: true
      conda_env_addl_pkgs:
        - c: conda-forge
          p: boto3
        - p: jupyter
    - role: '{{ playbook_dir }}'
      conda_env_name: ansible-conda-env-test
      conda_env_environment: ansible-conda-env-test-updated-environment.yml
      conda_env_cleanup: true
      conda_env_update_if_present: true
