---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: 'python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt;
        fi'
    - name: dcb anaconda
      run: dcb --upstreamregistry ghcr.io --upstreamgroup andrewrothstein --upstreamapp
        ansible-anaconda --snippet from.j2 ansible-test-role.j2 --pullall --writeall
        --buildall --alltags ${{ matrix.os }}
    - name: dcb miniconda
      run: dcb --upstreamregistry ghcr.io --upstreamgroup andrewrothstein --upstreamapp
        ansible-miniconda --targetapp ansible-conda-env-miniconda --snippet from.j2
        ansible-test-role.j2 --pullall --writeall --buildall --alltags ${{ matrix.os
        }}
    strategy:
      matrix:
        os:
        - archlinux_latest
        - debian_bullseye
        - fedora_36
        - fedora_37
        - rockylinux_8
        - rockylinux_9
        - ubuntu_bionic
        - ubuntu_focal
        - ubuntu_jammy
        python-version:
        - '3.10'
name: dcb
'on':
- push
